# Requests to test ledger server API.
# Separate requests with ###
###
#@server = http://127.0.0.1:8080
@server = http://localhost:8080

###
GET {{server}}/
###
GET {{server}}?command=reg assets:inve -b 2022-08-01
###
GET {{server}}/hello
###
{{server}}/ping
###
{{server}}/shutdown
